version: '3'

services:

  apiportal:
    image: api-portal-image
    container_name: api-portal
    depends_on:
      - sqlserver
    ports:
      - "3131:80"
    environment:
      - ConnectionString=sqlserver
    build:
      context: .
      dockerfile: src\Portal.DevTest.API\Dockerfile
      
  sqlserver:
    image: ivamneres/portal-db
    container_name: portal-db
    hostname: portal-db-server
    environment:
      - MSSQL_SA_PASSWORD=senha@123
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    expose:
      - "1433"
    ports:
      - "1433:1433"